/** Exact stable IDs for the original project's 66 generals, in pack/catalog order. */
export const FULL_GENERAL_IDS = [
  "cao_cao",
  "guo_jia",
  "si_ma_yi",
  "xia_hou_dun",
  "xu_chu",
  "zhang_liao",
  "zhen_ji",
  "guan_yu",
  "huang_yue_ying",
  "liu_bei",
  "ma_chao",
  "zhang_fei",
  "zhao_yun",
  "zhu_ge_liang",
  "da_qiao",
  "gan_ning",
  "huang_gai",
  "lu_xun",
  "lv_meng",
  "sun_quan",
  "sun_shang_xiang",
  "zhou_yu",
  "diao_chan",
  "hua_tuo",
  "lv_bu",
  "yuan_shu",
  "cao_ren",
  "huang_zhong",
  "wei_yan",
  "xia_hou_yuan",
  "xiao_qiao",
  "yu_ji",
  "zhang_jiao",
  "zhou_tai",
  "dian_wei",
  "pang_de",
  "pang_tong",
  "tai_shi_ci",
  "wo_long",
  "xun_yu",
  "yan_liang_wen_chou",
  "yuan_shao",
  "cao_pi",
  "dong_zhuo",
  "jia_xu",
  "lu_su",
  "meng_huo",
  "sun_jian",
  "xu_huang",
  "zhu_rong",
  "cai_wen_ji",
  "deng_ai",
  "jiang_wei",
  "liu_chan",
  "sun_ce",
  "zhang_he",
  "zhang_zhao_zhang_hong",
  "zuo_ci",
  "shen_cao_cao",
  "shen_guan_yu",
  "shen_lv_bu",
  "shen_lv_meng",
  "shen_si_ma_yi",
  "shen_zhao_yun",
  "shen_zhou_yu",
  "shen_zhu_ge_liang",
] as const;

export type FullGeneralId = (typeof FULL_GENERAL_IDS)[number];

export function isFullGeneralId(value: string): value is FullGeneralId {
  return (FULL_GENERAL_IDS as readonly string[]).includes(value);
}
